### ISSUE TITLE
Stardrop wont open

### ISSUE THREAD

**Issue by RodeoDust** [Floogen/Stardrop#204]
[log.txt](https://github.com/Floogen/Stardrop/files/15195582/log.txt)

stardrop lost the smapi pathway somehow and after I reset it, it wont open at all. asked the discord, they have no idea what happened. ive uninstalled, reinstalled, etc. help!

**Comment by LePatient87** [comment]
[log.txt](https://github.com/Floogen/Stardrop/files/15204054/log.txt)

I am having the same problem as this user.

Stardrop lost the pathway to smapi, I fixed it, and now it will not open at all. I have also uninstalled and reinstalled multiple times.

**Comment by RodeoDust** [comment]
still cant find a fix unfortunately. running it off steam for now but i hope it comes back up soon

**Comment by stuoofid** [comment]
Something simillar is going on with me, Ill try and launch stardrop and it'll show it on task manager then it will close itself. I reinstalled, tried administrator mode, allowed it on windows fire wall but nothing works.

**Comment by JohnWertz** [comment]
Having the same issue as described.

**Comment by JohnWertz** [comment]
Having the same issue as described.

**Comment by TangentAspect** [comment]
Having the same issue as described.

**Comment by Floogen** [comment]
This should be fixed with [v1.2.1](https://github.com/Floogen/Stardrop/releases/tag/v1.2.1), though I am unsure why the client data file became corrupted.

I added some additional logging in case the problem persists, so I will need another log file if you are still having issues.
