### ISSUE TITLE
Not correctly identifying mods needing updates

### ISSUE THREAD

**Issue by diannetea** [Floogen/Stardrop#36]
SMAPI log says 4 updates are available, but Stardrop does not show these updates.  It also appears to be showing a single mod as updateable but it does not show anything when "Show Updateable Mods" is checked.

![image_2022-01-13_110944](https://user-images.githubusercontent.com/3236694/149366294-20e1f5ff-686c-4f25-8935-80fa3791542b.png)

https://smapi.io/log/21a7cd2eb13846c6a8d7cf0d2f19af7d

[log.txt](https://github.com/Floogen/Stardrop/files/7864118/log.txt)

**Comment by Floogen** [comment]
This should now be fixed with v1.0.0-beta.22. Thank you for reporting this issue!

**Comment by diannetea** [comment]
It is still not correctly identifying that mods need to be updated.  SMAPI says 2 mods are updateable, but Stardrop can't find them.

[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/7964206/SMAPI-latest.txt)

**Comment by diannetea** [comment]
:(

Still not working with beta 25

Stardrop Log
[log.txt](https://github.com/Floogen/Stardrop/files/7983068/log.txt)

SMAPI Log
https://smapi.io/log/a04c9c84bc1f43f692ba8fa943013b4c

**Comment by Floogen** [comment]
I see the issue! I actually fixed the source of that problem with v1.0.0-beta.25, however it didn't resolve those currently affected (it only stops it from occurring for other people).

I'll have an update out shortly that should resolve this.
